# GitHub Actions CI/CD Pipeline
# .github/workflows/deploy.yml
name: Deploy Trading Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run tests
        run: mvn test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build application
        run: mvn clean package
      - name: Build Docker image
        run: docker build -t trading-bot:latest .
      - name: Push to registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag trading-bot:latest ${{ secrets.DOCKER_USERNAME }}/trading-bot:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/trading-bot:latest
